version: "2"
services:
  builder:
    image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    volumes:
      - ..:/plugin_dev
    working_dir: /plugin_dev/app-plugin-cian/tests
    command: /bin/bash -c "./build_local_test_elfs.sh"
